### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [anhcao142/polkadot-hackathon#1]
Hi anhcao142,

Thanks for your submission in our MetaMask challenge. Unfortunately, we can't read the addressToken from the checkContract you submitted. Could you share the checkContract that you submitted so I can provide feedback?

Regards
Alberto

**Comment by anhcao142** [comment]
Hi @albertov19 this is the checkContract address that I submitted.

`0x501e8b803FA2Da180137b17A14FB22509F66f01F `

**Comment by anhcao142** [comment]
Here is the checkContract.sol and I deployed it in `https://rpc.testnet.moonbeam.network`

```solidity
pragma solidity ^0.4.16;

contract checkContract {
    address public address1 = 0xC2273e233BbaA8ea4651F43CbAa2eF464030aa66;
    address public address2 = 0x94F652d16928C760DC93A6C8B6D09b3859599730;
    address public addressToken = 0x17a6CF4893F5C709C88f98c757d6361f1685A2f8;
}
```

**Comment by albertov19** [comment]
I was able to verify your submission.

Thanks!
